import fs from "node:fs"
import path from "node:path"

import type {
  IBrandProfileModel,
  IBrandRuleRecord,
  IBrandSkillCommand,
  IBrandSkillRunReport,
  IBrandSourceInventory,
  INormalizedBrandModel,
} from "../model/normalized-brand-model"
import { toWorkspaceRelativePath } from "../utils/workspace-paths"

const ensureDirectory = (filePath: string) => {
  fs.mkdirSync(path.dirname(filePath), { recursive: true })
}

const formatRuleList = (rules: IBrandRuleRecord[]) => {
  if (rules.length === 0) {
    return "- No rules synthesized yet."
  }

  return rules
    .map((rule) => {
      const sourceLine =
        rule.sourceIds.length > 0 ? `  Sources: ${rule.sourceIds.join(", ")}` : "  Sources: none"

      return `- ${rule.title}: ${rule.summary}\n${sourceLine}\n  Confidence: ${rule.confidence}\n  Why: ${rule.rationale}`
    })
    .join("\n")
}

const formatProfile = (profile: IBrandProfileModel) => {
  return `# ${profile.profileName}\n\nConfidence: ${profile.confidence}\n\n${formatRuleList(profile.rules)}\n`
}

const buildSkillEntrypoint = (command: IBrandSkillCommand, report: IBrandSkillRunReport) => `---
name: ${command.brandSlug}
description: Brand-specific generated skill for ${command.brandName}. Uses synthesized brand DNA, profiles, and reports generated by brand-skill-generator.
---

# ${command.brandName}

Generated brand skill bundle for ${command.brandName}.

## Use When

- You need brand-aware UI, copy, behavior, or design-system guidance for ${command.brandName}
- You want to inspect profile-specific rules before implementation
- You want the latest generated synthesis instead of a generic style doctrine

## Files

- core/brand-dna.md
- core/voice.md
- core/visual-system.md
- core/behavior.md
- core/source-policy.md
- profiles/design-system.md
- profiles/marketing.md
- profiles/product-ui.md
- profiles/dashboard.md
- report/report.md
- report/report.json
- report/changes.md

## Current Status

- Overall confidence: ${report.overallConfidence}
- Last mode: ${report.mode}
- Destination: ${report.destinationDir}
`

const buildSourcePolicy = (sourceInventory: IBrandSourceInventory) => {
  const sourceLines = sourceInventory.sourceRecords
    .map(
      (sourceRecord) =>
        `- ${sourceRecord.id} (${sourceRecord.sourceType}) -> ${sourceRecord.sourceSummary}`,
    )
    .join("\n")

  return `# Source Policy

Weighted hybrid priority:

1. explicit brand docs
2. live product or website behavior
3. designer artifacts and screenshots
4. derived signals from code or repeated patterns

## Sources In This Run

${sourceLines}
`
}

const buildReportMarkdown = (
  command: IBrandSkillCommand,
  sourceInventory: IBrandSourceInventory,
  normalizedBrandModel: INormalizedBrandModel,
  report: IBrandSkillRunReport,
) => {
  const sourceSections = sourceInventory.sourceRecords
    .map((sourceRecord) => {
      const discoveredLine =
        sourceRecord.discoveredPaths.length > 0
          ? `Discovered: ${sourceRecord.discoveredPaths.join(", ")}`
          : "Discovered: none"

      const notesLine =
        sourceRecord.notes.length > 0 ? `Notes: ${sourceRecord.notes.join(" | ")}` : "Notes: none"

      return `### ${sourceRecord.id}

- Type: ${sourceRecord.sourceType}
- Role: ${sourceRecord.sourceRole ?? "unspecified"}
- Location: ${sourceRecord.location}
- Summary: ${sourceRecord.sourceSummary}
- Confidence baseline: ${sourceRecord.explicitnessBaseline}
- ${discoveredLine}
- ${notesLine}`
    })
    .join("\n\n")

  return `# ${command.brandName} Synthesis Report

- Mode: ${report.mode}
- Destination: ${report.destinationDir}
- Overall confidence: ${report.overallConfidence}
- Preflight status: ${report.preflightStatus}

## Preflight

### Known Inputs

${report.preflightKnownInputs.length > 0 ? report.preflightKnownInputs.map((knownInput) => `- ${knownInput}`).join("\n") : "- None"}

### Missing Coverage

${report.preflightMissingCoverage.length > 0 ? report.preflightMissingCoverage.map((missingCoverage) => `- ${missingCoverage}`).join("\n") : "- None"}

### Ambiguities

${report.preflightAmbiguities.length > 0 ? report.preflightAmbiguities.map((ambiguity) => `- ${ambiguity}`).join("\n") : "- None"}

### Preflight Warnings

${report.preflightWarnings.length > 0 ? report.preflightWarnings.map((warning) => `- ${warning}`).join("\n") : "- None"}

## Source Summary

- Total sources: ${report.sourceSummary.totalSources}

## Sources

${sourceSections}

## Brand Identity

${formatRuleList(normalizedBrandModel.brandIdentity)}

## Voice

${formatRuleList(normalizedBrandModel.voice)}

## Visual System

${formatRuleList(normalizedBrandModel.visualSystem)}

## Interaction Behavior

${formatRuleList(normalizedBrandModel.interactionBehavior)}

## Design System

${formatRuleList(normalizedBrandModel.designSystem)}

## Conflicts

${normalizedBrandModel.conflicts.length > 0 ? normalizedBrandModel.conflicts.map((conflict) => `- ${conflict.summary}\n  Resolution: ${conflict.chosenDirection}\n  Suggested override: ${conflict.suggestedOverride ?? "None"}`).join("\n") : "- None"}

## Profiles

### design-system
${formatRuleList(normalizedBrandModel.profiles.find((profile) => profile.profileName === "design-system")?.rules ?? [])}

### marketing
${formatRuleList(normalizedBrandModel.profiles.find((profile) => profile.profileName === "marketing")?.rules ?? [])}

### product-ui
${formatRuleList(normalizedBrandModel.profiles.find((profile) => profile.profileName === "product-ui")?.rules ?? [])}

### dashboard
${formatRuleList(normalizedBrandModel.profiles.find((profile) => profile.profileName === "dashboard")?.rules ?? [])}

## Missing Source Suggestions

${report.missingSourceSuggestions.length > 0 ? report.missingSourceSuggestions.map((suggestion) => `- ${suggestion}`).join("\n") : "- None"}
`
}

const buildChangesMarkdown = (
  command: IBrandSkillCommand,
  changedFiles: string[],
  updateMode: "create" | "update",
) => {
  return `# Changes

- Mode: ${command.mode}
- Update mode: ${updateMode}
- Changed files: ${changedFiles.length}

${changedFiles.length > 0 ? changedFiles.map((filePath) => `- ${filePath}`).join("\n") : "- None"}
`
}

const buildReportJsonPayload = ({
  command,
  sourceInventory,
  normalizedBrandModel,
  report,
  updateMode,
}: {
  command: IBrandSkillCommand
  sourceInventory: IBrandSourceInventory
  normalizedBrandModel: INormalizedBrandModel
  report: IBrandSkillRunReport
  updateMode: "create" | "update"
}) => {
  return {
    command: {
      mode: command.mode,
      brandName: command.brandName,
      brandSlug: command.brandSlug,
      destinationDir: toWorkspaceRelativePath(command.workspaceRoot, command.destinationDir),
      websiteUrls: command.websiteUrls,
      docsPaths: command.docsPaths,
      screenshotPaths: command.screenshotPaths,
      codePaths: command.codePaths,
      figmaUrls: command.figmaUrls,
      dryRun: command.dryRun,
    },
    updateMode,
    sourceInventory,
    normalizedBrandModel,
    report,
  }
}

export const renderBrandSkillBundle = ({
  command,
  sourceInventory,
  normalizedBrandModel,
  report,
  updateMode,
}: {
  command: IBrandSkillCommand
  sourceInventory: IBrandSourceInventory
  normalizedBrandModel: INormalizedBrandModel
  report: IBrandSkillRunReport
  updateMode: "create" | "update"
}) => {
  const reportJsonPayload = buildReportJsonPayload({
    command,
    sourceInventory,
    normalizedBrandModel,
    report,
    updateMode,
  })
  const files = new Map<string, string>([
    [path.join(command.destinationDir, "SKILL.md"), buildSkillEntrypoint(command, report)],
    [
      path.join(command.destinationDir, "core", "brand-dna.md"),
      `# Brand DNA\n\n${formatRuleList(normalizedBrandModel.brandIdentity)}\n`,
    ],
    [path.join(command.destinationDir, "core", "voice.md"), `# Voice\n\n${formatRuleList(normalizedBrandModel.voice)}\n`],
    [
      path.join(command.destinationDir, "core", "visual-system.md"),
      `# Visual System\n\n${formatRuleList(normalizedBrandModel.visualSystem)}\n`,
    ],
    [
      path.join(command.destinationDir, "core", "behavior.md"),
      `# Behavior\n\n${formatRuleList(normalizedBrandModel.interactionBehavior)}\n`,
    ],
    [path.join(command.destinationDir, "core", "source-policy.md"), buildSourcePolicy(sourceInventory)],
    [
      path.join(command.destinationDir, "profiles", "design-system.md"),
      formatProfile(normalizedBrandModel.profiles.find((profile) => profile.profileName === "design-system")!),
    ],
    [
      path.join(command.destinationDir, "profiles", "marketing.md"),
      formatProfile(normalizedBrandModel.profiles.find((profile) => profile.profileName === "marketing")!),
    ],
    [
      path.join(command.destinationDir, "profiles", "product-ui.md"),
      formatProfile(normalizedBrandModel.profiles.find((profile) => profile.profileName === "product-ui")!),
    ],
    [
      path.join(command.destinationDir, "profiles", "dashboard.md"),
      formatProfile(normalizedBrandModel.profiles.find((profile) => profile.profileName === "dashboard")!),
    ],
    [
      path.join(command.destinationDir, "report", "report.md"),
      buildReportMarkdown(command, sourceInventory, normalizedBrandModel, report),
    ],
    [path.join(command.destinationDir, "report", "report.json"), `${JSON.stringify(reportJsonPayload, null, 2)}\n`],
  ])

  const changedFiles: string[] = []

  for (const [filePath, content] of files) {
    ensureDirectory(filePath)

    const previousContent = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : null

    if (previousContent !== content) {
      fs.writeFileSync(filePath, content)
      changedFiles.push(toWorkspaceRelativePath(command.workspaceRoot, filePath))
    }
  }

  const changesPath = path.join(command.destinationDir, "report", "changes.md")
  const changesMarkdown = buildChangesMarkdown(command, changedFiles, updateMode)
  ensureDirectory(changesPath)
  fs.writeFileSync(changesPath, changesMarkdown)

  return [
    ...changedFiles,
    toWorkspaceRelativePath(command.workspaceRoot, changesPath),
  ]
}
